### ISSUE TITLE
Unknown function: 'claudeMessages'.

### ISSUE THREAD

**Issue by khalidmaquilang** [anthropics/prompt-eng-interactive-tutorial#16]
Your tutorial isn't working
<img width="1488" alt="Screenshot 2024-10-17 at 11 07 30 PM" src="https://github.com/user-attachments/assets/cd8f5b50-a8fe-4137-83ec-e38bf3d5c680">

**Comment by khalidmaquilang** [comment]
i fixed it by turning off and on the `Use in this document`

**Comment by mkelchner** [comment]
Turning on and off the `Use in this document` didn't seem to work for me after repeated tries. I ended up uninstalling and reinstalling the extension and that appeared to fix this. It even seemed to retain my API key that I had set.
